version: "3.8"

services:
  graphql:
    build: .
    ports:
    - 6060:6060
    networks:
    - juniper-demo-net
    depends_on:
    - postgres
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    expose:
    - 5432
    networks:
    - juniper-demo-net

networks:
  juniper-demo-net:
    driver: bridge